### ISSUE TITLE
Error when trying to run the docker file

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/membrane-backend#61]
error message :

Traceback (most recent call last):
  File "/usr/local/bin/hypercorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hypercorn/__main__.py", line 287, in main
    run(config)
  File "/usr/local/lib/python3.11/site-packages/hypercorn/run.py", line 38, in run
    sockets = config.create_sockets()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hypercorn/config.py", line 203, in create_sockets
    insecure_sockets = self._create_sockets(self.bind)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hypercorn/config.py", line 266, in _create_sockets
    sock.bind(binding)

**Comment by k-allagbe** [comment]
Please add steps to reproduce.
